---
default:
  pipeline:
    Cloud-provider:
      - name: "GCP project name"
        description: "The GCP project name to use"
        key: gcp_project
        widget: simple_text
        type: string
        default: cycloid-demo
      - name: "GCP zone"
        key: gcp_zone
        widget: auto_complete
        type: string
        values: [asia-east1-a,asia-east1-b,asia-east1-c,asia-east2-a,asia-east2-b,asia-east2-c,asia-northeast1-a,asia-northeast1-b,asia-northeast1-c,asia-northeast2-a,asia-northeast2-b,asia-northeast2-c,asia-northeast3-a,asia-northeast3-b,asia-northeast3-c,asia-south1-a,asia-south1-b,asia-south1-c,asia-southeast1-a,asia-southeast1-b,asia-southeast1-c,australia-southeast1-a,australia-southeast1-b,australia-southeast1-c,europe-north1-a,europe-north1-b,europe-north1-c,europe-west1-b,europe-west1-c,europe-west1-d,europe-west2-a,europe-west2-b,europe-west2-c,europe-west3-a,europe-west3-b,europe-west3-c,europe-west4-a,europe-west4-b,europe-west4-c,europe-west6-a,europe-west6-b,europe-west6-c,northamerica-northeast1-a,northamerica-northeast1-b,northamerica-northeast1-c,southamerica-east1-a,southamerica-east1-b,southamerica-east1-c,us-central1-a,us-central1-b,us-central1-c,us-central1-f,us-east1-b,us-east1-c,us-east1-d,us-east4-a,us-east4-b,us-east4-c,us-west1-a,us-west1-b,us-west1-c,us-west2-a,us-west2-b,us-west2-c,us-west3-a,us-west3-b,us-west3-c,us-west4-a,us-west4-b,us-west4-c]
        default: "europe-west1-b"
      - name: "GCP json credentials"
        description: "GCP credentials in json format which should be used"
        key: gcp_credentials_json
        widget: cy_cred
        type: string
        default: "((gcp_step-by-step.json_key))"
    Application-code:
      - name: "Application git public url"
        description: "The url of the public GIT repository containing the source code of the application"
        key: code_git_public_repository
        widget: simple_text
        type: string
        default: "https://github.com/cycloid-community-catalog/docs-step-by-step-stack"
      - name: "Application git repository branch"
        description: "The branch of the public GIT repository containing the source code of the application"
        key: code_git_branch
        widget: simple_text
        type: string
        default: code
    Private-stack:
      - name: "Service catalog repository"
        description: "Service catalog repository containing your private stack"
        key: git_repository
        widget: cy_scs
        type: string
        default: git@github.com:cycloid-community-catalog/docs-step-by-step-stack.git
      - name: "Service catalog branch"
        description: "Branch to use containing the source code of your stack"
        key: stack_git_branch
        widget: cy_branch
        type: string
        source: git_repository
        default: azure
      - name: "Config catalog branch"
        description: "Branch to use which will contain the Configuration of your environment"
        key: config_git_branch
        widget: cy_branch
        type: string
        source: git_repository
        default: config
      - name: "Service catalog repository credential (SSH key)"
        description: "Credential (SSH key) used to fetch the service catalog of the stack"
        key: git_ssh_key
        widget: cy_cred
        type: string
        default: "((ssh_step-by-step.ssh_key))"
    Terraform:
      - name: "GCP object storage bucket name"
        description: "Name of the GCP object storage bucket used to store Terraform tfstate file"
        key: terraform_storage_bucket_name
        widget: simple_text
        type: string
        default: "($ organization_canonical $)-terraform-remote-state"
      - name: "GCP object storage bucket path"
        description: "The path in the GCP object storage bucket path used to store Terraform tfstate file"
        key: terraform_storage_bucket_path
        widget: simple_text
        type: string
        default: "($ project $)"
    Cycloid-API:
      - name: "Cycloid api url"
        description: "Url of the Cycloid API to use"
        key: api_url
        widget: simple_text
        type: string
        default: https://http-api.cycloid.io
      - name: "Cycloid api login"
        key: api_login
        widget: cy_cred
        type: string
        default: "((basic_auth_cyclobot-account.username))"
      - name: "Cycloid api password"
        key: api_password
        widget: cy_cred
        type: string
        default: "((basic_auth_cyclobot-account.password))"

  terraform:
    configuration:
      - name: "AWS instance type"
        description: "The type of instance you want to create"
        key: instance_type
        widget: slider_list
        type: string
        values:
        - n1-standard-1
        - n1-standard-2
        - n1-standard-4
        - n1-standard-8
        default: n1-standard-1
