groups:
  - name: all
    jobs:
    - build-application
    - unittest

resources:
  - name: git_lambda-code
    type: git
    check_every: 2m
    source:
      uri: ((lambda_git_repository))
      branch: ((lambda_git_branch))
      private_key: ((lambda_git_ssh_key))

  - name: s3_lambda-release
    type: s3
    source:
      bucket: ((lambda_release_bucket_name))
      versioned_file: ((lambda_release_bucket_object_path))
      private: true
      region_name: ((aws_default_region))
      access_key_id: ((aws_access_key))
      secret_access_key: ((aws_secret_key))

jobs:
  - name: build-application
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
    - do:
      - get: git_lambda-code
        trigger: true

      - task: build-release
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: cycloid/cycloid-toolkit
              tag: latest
          run:
            path: /bin/bash
            args:
            - -exc
            - |
              DIR=${PWD}
              cd ${DIR}/code/
              zip -r ${DIR}/release/((project)).zip *
          inputs:
          - name: git_lambda-code
            path: code
          outputs:
          - name: release
            path: "release"

      - put: s3_lambda-release
        params:
          acl: private
          file: release/((project)).zip

  - name: unittest
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
    - do:
      - get: git_lambda-code
        passed: [build-application]
      - get: s3_lambda-release
        trigger: true
        passed: [build-application]

      - task: test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: cycloid/cycloid-toolkit
              tag: latest
          run:
            path: /bin/bash
            args:
            - -exc
            - |
              unzip code/((project)).zip
          inputs:
          - name: s3_lambda-release
            path: code
