# Configuration of the CI pipeline
name: 'My ec2 stack'
canonical: 'stack-ec2'
description: 'Demo stack which create an AWS ec2 instance with terraform'
keywords:
  - 'aws'
  - 'ec2'
  - 'ansible'
  - 'demo'
technologies:
  - technology: Aws ec2 instance
    version: n/a
author: 'Cycloid'
image: 'https://raw.githubusercontent.com/cycloid-community-catalog/docs-step-by-step-stack/stacks/icon.png'
type: 'stack'
config:
  # Configuration of the CI pipeline
  pipeline:
    pipeline:
      path: 'pipeline/pipeline.yml'
    variables:
      path: 'pipeline/variables.sample.yml'
  # Configuration of terraform
  terraform:
    ec2:
      path: 'terraform/main.tf.sample'
      destination: '($ project $)/terraform/($ environment $)/main.tf'
  ansible:
    ec2:
      path: 'ansible/environments/ec2.yml.sample'
      destination: '($ project $)/ansible/environments/($ environment $)-ec2.yml'
